export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";
export const LOGOUT = "LOGOUT";
export const DELETE = "DELETE";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SET_MESSAGE_LOGIN = "SET_MESSAGE_LOGIN";
export const CLEAR_MESSAGE_LOGIN = "CLEAR_MESSAGE_LOGIN";
export const SET_MESSAGE_REGISTER = "SET_MESSAGE_REGISTER";
export const CLEAR_MESSAGE_REGISTER = "CLEAR_MESSAGE_REGISTER";

export const TICKETCOUNT_REMAINING_GET_SUCCESS = "TICKETCOUNT_REMAINING_GET_SUCCESS";
export const TICKETCOUNT_REMAINING_GET_FAILURE = "TICKETCOUNT_REMAINING_GET_FAILURE";
export const TICKET_UPDATE_SUCCESS = "TICKET_UPDATE_SUCCESS";
export const TICKET_UPDATE_FAILURE = "TICKET_UPDATE_FAILURE";

export const TOKEN_CONSUME_SUCCESS = "TOKEN_CONSUME_SUCCESS";
export const TOKEN_CONSUME_FAILURE = "TOKEN_CONSUME_FAILURE";
